mesaugat/tech-companies-in-nepal

README.md
=> add uxl in the list

README.md
=> Add Bidhee Pvt. Ltd.

README.md
Anubhabi Technologies Pvt. Ltd.
=> Add Anubhabi Technologies Pvt. Ltd.

README.md
-  Laser InfoTech 
-  Three Monks
=> Add Laser InfoTech & Three Monks

README.md
- Correction in Description of Bidhee Pvt. Ltd.
=> Correction in Bidhee Pvt. Ltd. description

README.md
=> Add Mhuchya Tech

README.md
=> Add Libresoft IT Solutions

README.md
=> Add IntroCept

README.md
=> Add sastodeal.com

README.md
=> Add Daanfe Inc

README.md
=> Adds Pagevamp and PeaceNepal

README.md
=> Add Tech Bizz Pvt. Ltd.

README.md
My twitter username was changed so previous link is broken. Fixed that.
=> Update link to twitter list

README.md
Added two companies: Verisk Nepal and InsightWorkshop
=> Add Insight Workshop and Verisk Nepal

README.md
Address updated for Three Monks
=> Update address of Three Monks

README.md
=> Add Unifun

README.md
* Enliv Information Technologies
=> Add Enliv IT

README.md
=> Add EagleVision IT

README.md
* Add IT Advisors Nepal
* Add QPay
=> Add IT Advisors Nepal and QPay

README.md
In this PR:
- Updated the location of Jyaasa
- Updated the description of Jyaasa
=> Updated jyaasa location and description

README.md
=> Add Mahuri Ventures

README.md
nepbix technology website added.
=> Add Nepbix Technology

README.md
=> Add 6 new companies to the list

README.md
* Add Tech Kunja
* Add Dafne Solution
=> Add Tech Kunja and Danfe Solution

README.md
* Add Aayulogic
* Add Curve n' Colors
=> Add Aayulogic and Curve n' Colors

README.md
=> Add Kazi Studios

README.md
=> Add InfoDevelopers

README.md
=> Add WebRobo

README.md
=> Add Smartmobe Solutions

README.md
=> Add Incwell Venture

README.md
=> Add HiUp Solutions

README.md
=> Add Rosebay Consulting

README.md
=> Add Tekkon Technologies

README.md
=> Add NepXpress Cargo & Courier

README.md
Verscend Technologies is now known as "Cotiviti Nepal".
=> Rename Verscend to Cotivity

README.md
Add the TechNepal portal (https://technepal.io) to the Readme.
=> Add TechNepal.io

README.md
- CellApp Innovations
- I3 Web Solution
- Susankya Tech Pvt. Ltd.
All these were found here 👉https://www.quora.com/What-are-some-software-companies-in-Kathmandu-that-provide-internships-to-IT-students?share=1
=> Add a few more companies

README.md
=> Add Comptech International

README.md
=> Add MPercept Technology

README.md
=> Add Tech One Global Pvt. Ltd.

README.md
Add Following companies:
- Asterdio Inc,
- Mandala Pvt. Ltd.
- Softhover
=> Add Asterdio, Mandala and Softhover

README.md
Add Iceberg Technology Pvt. Ltd.
=> Add Iceberg Technology Pvt. Ltd.

README.md
=> Add Sastra Creations

README.md
=> Add Okhati Solutions

README.md
=> Add Source Code Pvt. Ltd.

README.md
- Add Astranix Technologies Pvt. Ltd.
=> Add Astranix Technologies Pvt. Ltd.

README.md
I know this because I work here. :D
=> Change location of Enliv Technology

README.md
=> Add Cixware

README.md
- Add Sofwena Pvt. Ltd.
- Add Walkers Hive Pvt. Ltd.
=> Add Sofwena Pvt. Ltd. & Walkers Hive Pvt. Ltd.

README.md
@mesaugat I've added a link to a [repo](https://github.com/amitness/ml-companies-in-nepal), where I maintain a list of ML companies.
=> Add link to ml-companies-in-nepal

README.md
I have added link to Codewing Solutions
=> Added Codewing Solutions

README.md
Removed Goreto. It's not in operation
=> Removed Goreto

README.md
Removed nLocate since no longer in operation
=> Removed nLocate

README.md
* Add Code Kavya (IT Company from Pokhara) --> https://codekavya.com/
=> Add Code Kavya

README.md
I have removed the companies whose website are unreachable.
**Addition**
- E-Digital Nepal Pvt. Ltd.
- Young Minds Creation (P) Ltd
- Atlas Tek Pvt. Ltd
- Channakya Software (P) Ltd.
- Amsoft Technologies
- D-Tech Office System Pvt. Ltd.
**Removal** 
- big B Soft
- Itel Communications Pvt. Ltd.
- TECHRISE
=> Add a few more companies in operation and remove companies that no longer have a working website

README.md
Avionte Solutions is based in US and they don't have any offices in Nepal. They are outsourcing some of their tasks to Impetus Incorporation and they are the representative of Avionte Solutions in Nepal. I know this because my friend used to work at Impetus Incoporation.
=> Remove Avionte Solutions & Add Chhito Connect Pvt. Ltd.

README.md
Add webpoint solutions company located in sanepa
=> Add Webpoint Solutions

README.md
Added Pathway Technologies which is located at Thapathali, Kathmandu
=> Add Pathway Technologies

README.md
- Add Digital Age Nepal
- Add Sajilo Saathi
=> Add Digital Age Nepal and Sajilo Saathi

README.md
- Add SoAni Tech Pvt. Ltd.
- Update location of F1Soft
=> Add SoAni Tech and Update Location of F1Soft

README.md
[Ayat Digital Pvt. Ltd.](https://www.ayatdigital.com/)
=> add ayat digital pvt. ltd.

README.md
=> Add cyclone nepal

README.md
* Add Sofsee Tech and Neem Infosys from Mahendranagar, Kanchanpur, Sudurpaschim Nepal
=> Add Sofsee Tech & Neem Infosys from Sudurpaschim

README.md
The Next Coders http://thenextcoders.com added
=> Add "The Next Coders"

README.md
Made some changes on GitHub redirects and changes the website link from http:// to https:// as some links were not working.
=> Correct redirects

README.md
- Update location
- Update description
=> Update information about UXCam

README.md
**Add following companies**
1. Axios Softwork
2. HiTech Solutions & Services Pvt. Ltd.
3. Inficare
4. Progressive Labs Pvt. Ltd
5. Softbenz Infosys
=> Add more tech companies in Nepal

README.md
* Add SecurityPal
* Add Naxa
* Add Rara Labs
=> added security pal, naxa, rara labs company information

README.md
Add Codniv Innovations Pvt. Ltd.
=> Add Codniv Innovations

README.md
Added company SUNAI technology PVT.LTD
=> Add Sunai Technology

README.md
update readme to add waterflow technology
=> Add waterflow technology

README.md
add sursa and vurilo companies to the list.
=> Add sursa tech and vurilo

README.md
BatchNepal Consultancy was missing :)
=> Add batchnepal consultancy

README.md
=> Add Fleetpanda

README.md
This commit introduces the updated information of the location and what does Parewa Labs Pvt. Ltd. offer to users.
=> Update Parewa Labs Pvt. Ltd.

README.md
=> Remove Enliv Technology

README.md
- Blanxer Technologies Pvt. Ltd.
=> Add Blanxer Technologies Pvt. Ltd.

README.md
Added on the list :
- Company Name : Nepal Digital Systems Pvt. Ltd.
- Web: https://nepaldigisys.com/
- Address: Dhobighat, Lalitpur 
- About : A company working on IoT and Embedded Systems
=> Add Nepal Digital Systems

README.md
JyabaTech websraping company in Pokhara
=> Add JyabaTech

README.md
=> Add Avoloft

README.md
Cloudfactory's Nepalese branch has a different website and location on the website is Jhamsikhel, Lalitpur
=> Update Company Names and Location

README.md
=> add the infoxit.com company

README.md
Include Nimble Infosys in list
=> Include Nimble Infosys in list

README.md
=> Add Zookti

README.md
Added Company Saral Apps Pvt. Limited., An IT company of nepal who developed renouned apps of Nepal like Gurukul App for Gurukul CA, Lex Nepal App for Lex Nepal institution, TS Gurukul for Team Sandesh - Loksewa Tayari, Bright ACCA for Bright Academy, Hamro Academy for Hamro Academy with over 50 thounsands+ active Users and over 4.9 Star rating in Store ( For LexNepal and TS Gurukul)
=> Add Saral Apps Pvt. Ltd.
